//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightDetail
    {
        public string MaBooking { get; set; }
        public string MaFlight { get; set; }
        public string SoHieuChuyenBay { get; set; }
        public System.DateTime NgayBay { get; set; }
        public string DiemDi { get; set; }
        public string DiemDen { get; set; }
        public System.TimeSpan GioKhoiHanh { get; set; }
        public System.TimeSpan GioDen { get; set; }
        public decimal GiaVe { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
