//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDetail
    {
        public string MaBooking { get; set; }
        public string MaPhong { get; set; }
        public System.DateTime NgayNhanPhong { get; set; }
        public System.DateTime NgayTraPhong { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
