//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VietTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourDetail
    {
        public string MaBooking { get; set; }
        public string MaTour { get; set; }
        public int SoLuongNguoi { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
